lines = []
lines.append('using System.Windows;')
lines.append('using System.Windows.Controls;')
lines.append('using System.Windows.Input;')
lines.append('using System.Windows.Media;')
lines.append('using System.Windows.Shapes;')
lines.append('using System.Windows.Threading;')
lines.append('using Excalibur5.ViewModels;')
lines.append('')
lines.append('namespace Excalibur5.Views.Controls;')
lines.append('')
lines.append('public partial class MarketTabView : UserControl')
lines.append('{')
lines.append('    private Polyline? _chartLine;')
lines.append('    private Line? _crosshairLine;')
lines.append('    private DispatcherTimer? _redrawTimer;')
lines.append('    private int _zoomLevel;')
lines.append('    private int _viewEnd = -1;')
lines.append('')
lines.append('    public MarketTabView()')
lines.append('    {')
lines.append('        InitializeComponent();')
lines.append('        DataContextChanged += OnDataContextChanged;')
lines.append('        SizeChanged        += OnSizeChanged;')
lines.append('')
lines.append('        _redrawTimer = new DispatcherTimer')
lines.append('        {')
lines.append('            Interval = TimeSpan.FromMilliseconds(100)')
lines.append('        };')
lines.append('        _redrawTimer.Tick += (_, _) =>')
lines.append('        {')
lines.append('            _redrawTimer.Stop();')
lines.append('            RedrawChart();')
lines.append('        };')
lines.append('    }')
lines.append('')
lines.append('    private MarketTabViewModel? Vm => DataContext as MarketTabViewModel;')
with open('MarketTabView.xaml.cs', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('part1 done')
